In [58]:
print("hello")

hello


In [59]:
import random
import numpy as np


In [60]:
list1 = []
for i in range(2):
    list1.append(np.random.randint(9))
   
r1 = np.array(list1)


print(r1)


[3 7]


In [61]:
temp = [r1[0], 0]
x_comp=temp
temp = [0, r1[1]]
y_comp=temp

In [62]:
print(x_comp)
print(y_comp)

[3, 0]
[0, 7]


In [63]:
import math

def dotproduct(v1, v2):
  return sum((a*b) for a, b in zip(v1, v2))

def length(v):
  return math.sqrt(dotproduct(v, v))


def angle(v1, v2):
  return math.acos(dotproduct(v1, v2) / (length(v1) * length(v2)))

# Angle Theta

In [64]:
theta = angle(r1,x_comp)
print(theta)

1.1659045405098132


# Initial Vector using components

In [66]:
#generating vector from components 

og_vect = np.array([x_comp[0], y_comp[1]])
og_vect

array([3, 7])

# Iris Data Set

In [70]:
from sklearn.datasets import load_iris
df=load_iris()
df

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [80]:
import numpy as np
print(np.shape(df['data'][:4]))

w, v = np.linalg.eig(df['data'][:4])

print("Printing the Eigen values of the given square array:\n",w)

print("Printing Right eigenvectors of the given square array:\n",v)


(5, 4)
Printing the Eigen values of the given square array:
 [ 9.83727522 -0.25061646  0.05726033 -0.0439191 ]
Printing Right eigenvectors of the given square array:
 [[-0.52955642  0.45570445 -0.10972786  0.05072119]
 [-0.49369692 -0.82342212  0.02810628 -0.02712648]
 [-0.48800707  0.32839825  0.18552805 -0.25638252]
 [-0.48752687 -0.08039939  0.97608871  0.96486243]]


# Zero centered DataSet

In [86]:
Mean = [np.mean(df['data'][:,0]),np.mean(df['data'][:,1]),np.mean(df['data'][:,2]),np.mean(df['data'][:,3])]
Mean

[5.843333333333334, 3.0573333333333337, 3.7580000000000005, 1.1993333333333336]

In [94]:
no = np.shape(df['data'])
mean_sub = []

for i in range(150):
    mean_sub.append(Mean)
    
ms = np.array(mean_sub)
ms

zero_centered_df = df['data']-ms
zero_centered_df


array([[-7.43333333e-01,  4.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01, -5.73333333e-02, -2.35800000e+00,
        -9.99333333e-01],
       [-1.14333333e+00,  1.42666667e-01, -2.45800000e+00,
        -9.99333333e-01],
       [-1.24333333e+00,  4.26666667e-02, -2.25800000e+00,
        -9.99333333e-01],
       [-8.43333333e-01,  5.42666667e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-4.43333333e-01,  8.42666667e-01, -2.05800000e+00,
        -7.99333333e-01],
       [-1.24333333e+00,  3.42666667e-01, -2.35800000e+00,
        -8.99333333e-01],
       [-8.43333333e-01,  3.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.44333333e+00, -1.57333333e-01, -2.35800000e+00,
        -9.99333333e-01],
       [-9.43333333e-01,  4.26666667e-02, -2.25800000e+00,
        -1.09933333e+00],
       [-4.43333333e-01,  6.42666667e-01, -2.25800000e+00,
        -9.99333333e-01],
       [-1.04333333e+00,  3.42666667e-01, -2.15800000e+00,
      

# For ECG data

In [97]:
import pandas as pd

df = pd.read_csv('ECG200_TRAIN.csv', delimiter="  ", header=None)
df

C:\Users\A1D\anaconda3\lib\site-packages\pandas\util\_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


0         1         2         3         4         5         6         7   \
0  -1.0  0.502055  0.542163  0.722383  1.428885  2.136516  2.281149  1.936274   
1   1.0  0.147647  0.804668  0.367771  0.243894  0.026614 -0.274402  0.096731   
2  -1.0  0.316646  0.243199  0.370471  1.063738  1.678187  1.759558  1.697717   
3  -1.0  1.168874  2.075901  1.760141  1.606446  1.949046  1.302842  0.459332   
4   1.0  0.648658  0.752026  2.636231  3.455716  2.118157  0.520620 -0.188627   
..  ...       ...       ...       ...       ...       ...       ...       ...   
95  1.0  0.581277  0.876188  1.042767  1.796120  2.541399  2.246653  1.500387   
96 -1.0  2.689017  2.708703  2.008381  2.235800  1.516982  0.029916 -0.561346   
97 -1.0  0.197677  0.455417  0.973110  1.935956  2.259463  1.741341  1.158296   
98  1.0  0.179500  1.038409  1.946421  2.705141  1.670706 -0.101167 -1.578876   
99  1.0  0.073124  0.776054  2.181336  3.440325  2.168475  0.497315 -0.924284   

          8         9   ...        87        88        89        90        91  \
0   1.468890  1.008845  ...  0.931043  0.610298  0.638894  0.684679  0.583238   
1  -0.747731 -1.609777  ... -0.533503 -0.400228  0.176084  1.111768  2.438428   
2   1.612159  1.168188  ...  0.764229  0.610621  0.552900  0.566786  0.604002   
3   0.516412  0.852180  ...  0.419006  0.723888  1.323947  2.136488  1.746597   
4   0.780818  0.933775  ... -0.097869 -0.136787 -0.340237 -0.089441 -0.080297   
..       ...       ...  ...       ...       ...       ...       ...       ...   
95  1.031521  0.382672  ...  1.002770  0.907869  0.916457  0.923975  0.767357   
96 -0.793702 -0.979371  ... -0.136610 -0.072176 -0.082738 -0.138468 -0.120396   
97  0.418241 -0.071605  ...  0.482452  0.325569  0.247991  0.184127  0.050358   
98 -0.750906  0.175310  ...  0.324323  0.330489  0.111953  0.448948  0.567132   
99 -1.499227 -0.679328  ... -0.058935 -0.130638 -0.347235 -0.177933 -0.060332   

          92        93        94        95        96  
0   0.640522  0.708585  0.705011  0.713815  0.433765  
1   2.734889  1.736054  0.036857 -1.265074 -0.208024  
2   0.777068  0.812345  0.748848  0.818042  0.539347  
3   1.470220  1.893512  1.256949  0.800407  0.731540  
4  -0.192584 -0.304704 -0.454556  0.314590  0.582190  
..       ...       ...       ...       ...       ...  
95  0.656223  0.762357  0.501373 -0.333336 -0.524546  
96 -0.089411 -0.243141 -0.119710  0.124042  0.273463  
97  0.241988  0.331451 -0.120006  0.042423  0.343293  
98  0.136757  0.444768  0.151050  0.193378  0.451709  
99 -0.347634 -0.447443 -0.066689 -0.178448 -0.256052  

[100 rows x 97 columns]

In [100]:
Mean=[]


for i in range(0,97):
    Mean.append(np.mean(df.iloc[:,i]))
Mean
np_mtrx = np.array(Mean)


In [102]:
zero_centered_df = df-np_mtrx
zero_centered_df

0         1         2         3         4         5         6   \
0  -1.38 -0.206382 -0.879988 -1.316766 -0.697570  0.584900  1.518898   
1   0.62 -0.560791 -0.617483 -1.671378 -1.882561 -1.525002 -1.036653   
2  -1.38 -0.391791 -1.178952 -1.668678 -1.062717  0.126571  0.997307   
3  -1.38  0.460437  0.653750 -0.279009 -0.520009  0.397429  0.540591   
4   0.62 -0.059780 -0.670125  0.597082  1.329261  0.566541 -0.241631   
..   ...       ...       ...       ...       ...       ...       ...   
95  0.62 -0.127161 -0.545964 -0.996382 -0.330335  0.989783  1.484402   
96 -1.38  1.980580  1.286552 -0.030768  0.109345 -0.034635 -0.732334   
97 -1.38 -0.510761 -0.966735 -1.066039 -0.190499  0.707847  0.979090   
98  0.62 -0.528937 -0.383742 -0.092728  0.578686  0.119090 -0.863417   
99  0.62 -0.635313 -0.646097  0.142187  1.313870  0.616859 -0.264935   

          7         8         9   ...        87        88        89        90  \
0   1.653627  1.135260  0.635872  ...  0.740631  0.436013  0.433787  0.398194   
1  -0.185917 -1.081360 -1.982750  ... -0.723915 -0.574514 -0.029023  0.825284   
2   1.415070  1.278529  0.795215  ...  0.573817  0.436336  0.347793  0.280302   
3   0.176684  0.182782  0.479207  ...  0.228595  0.549602  1.118840  1.850003   
4  -0.471274  0.447189  0.560802  ... -0.288281 -0.311073 -0.545344 -0.375926   
..       ...       ...       ...  ...       ...       ...       ...       ...   
95  1.217740  0.697891  0.009699  ...  0.812359  0.733583  0.711350  0.637491   
96 -0.843993 -1.127332 -1.352344  ... -0.327022 -0.246462 -0.287845 -0.424952   
97  0.875649  0.084611 -0.444578  ...  0.292040  0.151284  0.042884 -0.102357   
98 -1.861523 -1.084535 -0.197663  ...  0.133911  0.156203 -0.093154  0.162464   
99 -1.206931 -1.832856 -1.052301  ... -0.249347 -0.304924 -0.552342 -0.464417   

          91        92        93        94        95        96  
0   0.170774  0.181145  0.318733  0.422147  0.530986  0.258901  
1   2.025964  2.275512  1.346202 -0.246008 -1.447904 -0.382888  
2   0.191538  0.317691  0.422493  0.465984  0.635213  0.364484  
3   1.334133  1.010844  1.503660  0.974085  0.617577  0.556677  
4  -0.492761 -0.651961 -0.694557 -0.737420  0.131761  0.407326  
..       ...       ...       ...       ...       ...       ...  
95  0.354893  0.196847  0.372505  0.218509 -0.516166 -0.699409  
96 -0.532860 -0.548788 -0.632993 -0.402574 -0.058787  0.098600  
97 -0.362106 -0.217388 -0.058402 -0.402870 -0.140407  0.168430  
98  0.154668 -0.322619  0.054916 -0.131814  0.010548  0.276845  
99 -0.472796 -0.807010 -0.837295 -0.349553 -0.361277 -0.430915  

[100 rows x 97 columns]

In [108]:
df2=df.iloc[:97,]
w, v = np.linalg.eig(df2)

print("Printing the Eigen values of the given square array:\n",w)

print("Printing Right eigenvectors of the given square array:\n",v)

Printing the Eigen values of the given square array:
 [-6.82171438e-01+5.09154653j -6.82171438e-01-5.09154653j
 -4.80656197e+00+0.j          6.90739450e-01+4.38749013j
  6.90739450e-01-4.38749013j  4.08282213e+00+0.j
 -2.38704040e+00+2.45944591j -2.38704040e+00-2.45944591j
 -2.88765246e+00+1.00662288j -2.88765246e+00-1.00662288j
  2.35208382e+00+1.48830841j  2.35208382e+00-1.48830841j
 -1.77891891e+00+1.76168523j -1.77891891e+00-1.76168523j
  1.85563900e-02+2.42542285j  1.85563900e-02-2.42542285j
 -1.83814244e+00+0.j          2.02677080e+00+0.25087648j
  2.02677080e+00-0.25087648j  2.03282659e+00+0.j
  6.89773418e-01+1.76568722j  6.89773418e-01-1.76568722j
  1.19971044e+00+1.44009865j  1.19971044e+00-1.44009865j
 -8.05023573e-01+1.60187976j -8.05023573e-01-1.60187976j
  1.70177942e+00+0.j         -1.31026183e+00+0.54002338j
 -1.31026183e+00-0.54002338j  7.99522778e-01+1.01270386j
  7.99522778e-01-1.01270386j  1.26774913e+00+0.j
  9.23476979e-01+0.82162257j  9.23476979e-01-0.82162257j
 